### ISSUE TITLE
Simplify massive enums for sign assets chooser

### ISSUE THREAD

**Issue by IodaMikeMapbox** [mapbox/vision-ios-examples#87] opened 2019-06-11 22:33 UTC
It is hard to maintain `Signs` class with all the assets images, I think we could write smart enough code to get rid of maintain it manually or at least make it simpler by providing dictionaries of assets and the file will become three times smaller. For now the code contains heavy boilerplate and a lot of copy/paste code

**Comment by dersim-davaod** [comment] 2019-06-11 22:38
A subtask for mapbox/mapbox-vision-ios#122

**Comment by chezzdev** [comment] 2020-02-07 12:40
Closing as a duplicate of https://github.com/mapbox/vision-ios-examples/issues/131

**Closed by chezzdev** 2020-02-07 12:40 UTC
Labels: iOS
